name: Update Instances
concurrency: osb-instances # signal that we're modifying instances (status/gemerated tf=)

env:
  # Use Github Repository Secrets to set your credentials.
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

on:
  # run on any push to master
  push:
    branches:
      - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process-vnets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup unipipe
        uses: meshcloud/setup-unipipe@v1 
      - name: checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@master
      ### Doing actual VNet Stuff
      - name: transform-vnets
        run: |
          unipipe --version
          unipipe list ./
          unipipe transform --registry-of-handlers=network/network-handlers.js ./
      - name: Configure git for VNet Bot
        run: |
          git config --global user.email "azure-platform-operators@example.com"
          git config --global user.name "VNet Bot by example.com"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: create-vnets
        run: |
          git checkout master
          chmod +x network/create-vnets.sh
          network/create-vnets.sh
          git add .
          git diff-index --quiet HEAD || git commit -m "Updating VNets"
          git push
